apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  {{- template "zero2prod.labels" . }}
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  APP_DATABASE__PASSWORD: {{ .Values.postgresql.auth.password | b64enc }}