apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: zero2prod
  ports:
    - port: {{ .Values.application.port }}
      targetPort: http
      protocol: TCP
      name: http